version: '3.7'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8310:80"
            - "4410:443"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs/nginx/:/var/log/nginx:cached
        depends_on:
            - php
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: twitterblog_php
        user: "${UID}"
        volumes:
          - ./:/var/www
          - ./data/composer:/.composer
          - ./logs/symfony:/var/www/var/logs:cached
        depends_on:
            - mysql
            - redis
    redis:
        image: redis:latest
        ports:
          - "6310:6379"
    mysql:
        image: mysql:5.7.21
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "8910:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
