<?php

namespace App\DataFixtures;

use App\Entity\MicroPost;
use App\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class AppFixtures extends Fixture
{
    /**
     * @var UserPasswordEncoderInterface
     */
    private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    public function load(ObjectManager $manager)
    {
        $this->loadUsers($manager);
        $this->loadMicroPosts($manager);
    }

    private function loadMicroPosts(ObjectManager $manager)
    {
        for ($i = 0; $i < 10; $i++) {
            $microPost = new MicroPost();
            $microPost->setText(
                'Some random text '.rand(
                    0,
                    100
                )
            );
            $microPost->setTime(new \DateTime('2018-03-15'));
            $microPost->setUser($this->getReference('maksim_test'));
            $manager->persist($microPost);
        }

        $manager->flush();
    }

    private function loadUsers(ObjectManager $manager)
    {
        $user = new User();
        $user->setUsername('maksim');
        $user->setFullName('Maksim Narushevich');
        $user->setEmail('maksim@gmail.com');
        $user->setPassword(
            $this->passwordEncoder->encodePassword(
                $user,
                'maksimqwerty'
            )
        );

        //-- Create reference and fetch if when seed micro posts
        //-- IT CAN BE ANY NAME OR EVEN AUTOGENERATED
        $this->addReference('maksim_test',$user);

        $manager->persist($user);
        $manager->flush();
    }
}